// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManager.Models;

#nullable disable

namespace StudentManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811071301_ValidteStudentModel")]
    partial class ValidteStudentModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManager.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            Name = "IT"
                        },
                        new
                        {
                            DeptId = 2,
                            Name = "CS"
                        },
                        new
                        {
                            DeptId = 3,
                            Name = "IS"
                        },
                        new
                        {
                            DeptId = 4,
                            Name = "AI"
                        });
                });

            modelBuilder.Entity("StudentManager.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Alexandria",
                            Age = 20,
                            DeptId = 1,
                            Email = "ahmed@gmail.com",
                            Name = "Ahmed",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ismailia",
                            Age = 24,
                            DeptId = 1,
                            Email = "ali@gmail.com",
                            Name = "Ali",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Cairo",
                            Age = 26,
                            DeptId = 1,
                            Email = "mohamed@gmail.com",
                            Name = "Mohamed",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ismailia",
                            Age = 22,
                            DeptId = 2,
                            Email = "salah@gmail.com",
                            Name = "Salah",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Sinai",
                            Age = 27,
                            DeptId = 2,
                            Email = "ziad@gmail.com",
                            Name = "Ziad",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Ismailia",
                            Age = 29,
                            DeptId = 2,
                            Email = "mahmoud@gmail.com",
                            Name = "Mahmoud",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Sinai",
                            Age = 21,
                            DeptId = 3,
                            Email = "osama@gmail.com",
                            Name = "Osama",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Ismailia",
                            Age = 20,
                            DeptId = 3,
                            Email = "ezz@gmail.com",
                            Name = "Ezz",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Cairo",
                            Age = 24,
                            DeptId = 4,
                            Email = "mazen@gmail.com",
                            Name = "Mazen",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Sinai",
                            Age = 24,
                            DeptId = 4,
                            Email = "eid@gmail.com",
                            Name = "Eid",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Ismailia",
                            Age = 28,
                            DeptId = 4,
                            Email = "hagag@gmail.com",
                            Name = "Hagag",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Cairo",
                            Age = 23,
                            DeptId = 4,
                            Email = "abdelrahman@gmail.com",
                            Name = "Abdelrahman",
                            Password = "123456"
                        });
                });

            modelBuilder.Entity("StudentManager.Models.Student", b =>
                {
                    b.HasOne("StudentManager.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentManager.Models.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
